#!/bin/bash

# DEBUG OPTIONS:
#set -x # trace complete output
set -e # stop if one command fails
set -u # no undefined/empty variables allowed
set -o pipefail # stop if one pipe fails
LOG=true

# ===============================================
# VARIABLES
# ===============================================
WORK="$(dirname $(readlink -f $0))"
LOGFILE="$WORK/build.log"
source $WORK/version

MNT="/mnt/rootfs"
ROOTFS="$MNT"
BOOT="$MNT/boot"

PACKAGES=$(tr ' \n' ' ' < $WORK/config/packages.txt)
PACKAGES=$(tr ' \n' ' ' < $WORK/config/packages-debian.txt)

CHROOT="arch-chroot /mnt/usb"
CHROOTCMD="arch-chroot"

HOSTNAME=superman
USER=polar
ROOTPW="evis32"

STRAPCMD="pacstrap $MNT $PACKAGES" 
STRAPCMD="debootstrap --include $PACKAGES --arch amd64 bullseye /mnt/usb"

# ===============================================
# CLI INTERFACE
# ===============================================

# OPTIONS (DEFAULT)
UNMOUNT="NO"
FULLWIPE="NO"
FULLBUILD="NO"
BASEBUILD="NO"
UPDATE_TUI="NO"
UPDATE_CONFIG="NO"
ENTER_CHROOT="NO"
TARGET=""

function about() 
{
  echo""  
  echo "┌──────────────────────────────────────────────────┐"
  echo "│ Debian Live on USB - Image Creator               │"
  echo "│ ------------------------------------------------ │"
  echo "│ Author:   S. Reddy                               │"
  echo "│ Version:  ${DEBIAN_VERSION}                                    │"
  echo "│ ------------------------------------------------ │"
  echo "│ Purpose:  Swiss Army Knife with tui for          │"
  echo "│           arch install, backup & tools           │"
  echo "└──────────────────────────────────────────────────┘"
  echo""
}

function usage() 
{
    
  echo "┌──────────────────────────────────────────────────┐"
  echo "  USAGE: "
  echo "    $(basename $0) [options] [target]               "
  echo
  echo "  OPTIONS:"
  echo "   -f, --fullbuild    build to target </mnt/<sdX>"
  echo "   -b, --basebuild    build to target </mnt/<sdX>"
  echo "   -w, --fullwipe     wipe USB drive  </mnt/<sdX>"
  echo "   -c, --chroot       enter chroot    </mnt/<sdX>"
  echo
  echo "   --update-tui       copy tui files to </mnt/<sdX>"
  echo "   --update-config    update config on </mnt/<sdX>"
  echo
  echo "   -v, --version      Show $(basename $0) version"
  echo "   -h, --help         This help dialog"
  echo "└──────────────────────────────────────────────────┘"
  echo ""
}

function version()
{
  echo "$(basename $0) - version: ${DEBIAN_VERSION}"
}

POSITIONAL=()
while [[ $# -gt 0 ]]
do
    key="$1"
    case $key in
        -f|--fullbuild)
            FULLBUILD="YES"
            TARGET="$2"
            shift
            shift
            ;;
        -b|--base-system)
            BASEBUILD="YES"
            TARGET="$2"
            shift
            shift
            ;;
        --update-tui)
            UPDATE_TUI="YES"
            TARGET="$2"
            shift
            shift
            ;;
        --update-config)
            UPDATE_CONFIG="YES"
            TARGET="$2"
            shift
            shift
            ;;
        -w|--fullwipe)
            FULLWIPE="YES"
            TARGET="$2"
            shift
            ;;
        -c|--chroot)
            ENTER_CHROOT="YES"
            TARGET="$2"
            shift
            shift
            ;;
        -u|--unmount)
            UNMOUNT="YES"
            TARGET="$2"
            shift
            shift
            ;;
        -v|--version)
            version
            exit 0
            shift
            ;;         
        -h|--help)
            about
            usage
            exit 0
            shift
            ;;
        *)    # unknown option
            POSITIONAL+=("$1") # save it in an array for later
            echo "ERROR: Unknown argument: ${POSITIONAL}"
            usage
            exit 1
            shift
            ;;
    esac
done
set -- "${POSITIONAL[@]}" # restore positional parameters



# ===============================================
# CHECKS
# ===============================================
# root check 
[ $(whoami) != root ] && echo "You must be root!" && exit 1

# check for empty target
#[ -z $TARGET ] && echo -e "You must specify a target. Determine the target USB device name with lsblk first!\n" && usage && exit 1

# clean log 
[ $LOG == true ] && [ -f $LOGFILE ] && rm $LOGFILE





# ===============================================
# FUNCTIONS
# ===============================================
function log()
{
  echo "$1"
  [ $LOG == true ] && echo "$1" >> $LOGFILE
}

function error()
{
  echo "$1"
  [ $LOG == true ] && echo "$1" >> $LOGFILE
  exit 1
}

function lognl()
{
	echo
	echo "=========================================="
	echo " STEP: $1"
	echo "=========================================="
}

function err()
{
	echo
	echo "=========================================="
	echo " ERROR:       $1"
	echo " FROM:        $0"
	echo "=========================================="
	exit 1
}

#================ MOUNTING ===================#
function unmounting()
{
  lognl "Unmount ..."

  if mountpoint -q $BOOT; then
    log "==> $BOOT is still mounted!"
    umount $BOOT && log "Unmount $BOOT sucessfull!" || error "Failed to unmount $BOOT" 
  fi
  
  if mountpoint -q $MNT; then
    log "==> $MNT is still mounted!"
    umount $MNT && log "Unmount $MNT successful!" || error "Failed to unmount $MNT"
  fi

  if mountpoint -q $MNT; then
  log "==> $MNT is still mounted!"
  umount $MNT && log "Unmount $MNT successful!" || error "Failed to unmount $MNT"
  fi

  log "==> Unmounting done!" && log ""
}

function unmountall()
{
  lognl "Unmount ..."
  mountpoint -q $MNT && umount -A ${TARGET}* || log "No device mounted!"
}

function mounting()
{
  lognl "Mounting ..."
  mkdir -p "$MNT" && log "Creating rootfs mountpoint $MNT done!"
  mount ${TARGET}2 $MNT && log "Mounting ${TARGET}2 on $MNT as done!" || error "Mounting ${TARGET}3 on $MNT failed!"
}


#================ PARTITIONING ===================#
function partioning()
{ 
  lognl "Partioning ..." 
  log "Clear partion data and create new partion table!"
  sgdisk -Z ${TARGET}
  sgdisk -o -n 1:0:+10M   -t 1:EF02 \
            -n 2:0:+3G    -t 2:8300 \
            -n 3:0:0      -t 3:8300 \
            ${TARGET}

  log "Wipe ${TARGET}"
  wipefs -a ${TARGET}2
  wipefs -a ${TARGET}3

  lognl "Formating ..."
  # Hint: Do not format the /dev/sdX1 block. This is the BIOS/MBR parition."
  
  # Format the Linux partition with an ext4 filesystem:
  mkfs.ext4 -q ${TARGET}2 && log "Creating ${TARGET}3 fs done!"

  # Format the data partition with an exfat/ntfs filesystem:
  mkfs.ext4 -q ${TARGET}3 && log "Creating ${TARGET}4 fs done!"
}

function fullwipe()   # optional
{
  lognl "Full wipe ..."
  log "This may take long time depending on disk size (1 hour+)"
  dd if=/dev/zero of=$TARGET status=progress && sync && log "Wiping done!"
  #dd if=/dev/zero of=$TARGET bs=16M status=progress && sync && log "==> Wiping done!"
}

#================ BASE SYSTEM ===================#

function basesystem()
{
  lognl "Install base system ..."
  $STRAPCMD && log "==> Base system installed!" && log ""
}


#==============================================#
# CONFIGURE
#==============================================#

function fstabgen()
{
  lognl "Generate fstab ..."
  # Generate a new /etc/fstab using UUIDs as source identifiers
  genfstab -U ${ROOTFS} > ${ROOTFS}/etc/fstab && \
  cat ${ROOTFS}/etc/fstab && \
  log "==> Generating fstab done!" || error "==> Generating fstab failed!"
}


function localecfg()
{
  lognl "Configure time ..."
  chroot ln -sf /usr/share/zoneinfo/Europe/Berlin /etc/localtime && log "==> Set timezone !" || err "Failed to set timezone!"
  chroot hwclock --systohc && log "==> Generate /etc/adjtime (hwclock)" || err "Failed to set /etc/adjtime!"

  lognl "Configure language & keyboard ..."
  $CHROOT sed -i 's/#de_DE.UTF-8 UTF-8/de_DE.UTF-8 UTF-8/g' /etc/locale.gen
  chroot locale-gen
  chroot echo "LANG=de_DE.UTF-8" > /etc/locale.conf
  chroot echo "KEYMAP=de-latin1" > /etc/vconsole.conf
}

#================ USER-CFG ===================#

function hostcfg()
{
  lognl "Configure hostname & hosts ..."
  chroot echo ${HOSTNAME} > /etc/hostname && log "==> set hostname to ${HOSTNAME}" || err "Failed to set hostname!"

cat <<EOF > ${ROOTFS}/etc/hosts
127.0.0.1  localhost
::1        localhost
127.0.1.1  ${HOSTNAME}.localdomain  ${HOSTNAME}"
EOF
}




#================ BOOTLAODER ===================#

function arch_bootloader()
{
  lognl "Install Bootloader"
#cat << EOF | $CHROOT
#grub-install --target=i386-pc --recheck ${TARGET} && \
#grub-install --target=x86_64-efi --efi-directory /boot --recheck --removable && \
#grub-mkconfig -o /boot/grub/grub.cfg
#EOF

  $CHROOT grub-install --force --target=i386-pc --recheck ${TARGET}
  $CHROOT grub-install --force --target=x86_64-efi --efi-directory /boot --recheck --removable
  $CHROOT grub-mkconfig -o /boot/grub/grub.cfg
}

function bootloader()
{
  lognl "Install Bootloader"
  chmod -x "${ROOTFS}/etc/grub.d/30_os-prober"
  chroot  "${ROOTFS}" grub-install --force ${TARGET}
  chroot "${ROOTFS}" update-grub
}

function newmkinitcpio()
{
 echo "TODO"
}

#================ END::BOOTLAODER ===================#

function networkcfg()
{
lognl "Configure network (wired)"

cat << EOF > $ROOTFS/etc/systemd/network/10-ethernet.network
[Match] 
Name=en*      
Name=en* 
Name=eth* 

[Network] 
DHCP=yes 
IPv6PrivacyExtensions=yes   

[DHCPv4] 
RouteMetric=10 

[IPv6AcceptRA]
RouteMetric=10
EOF

  lognl "Enable networking services ..."
  chroot systemctl enable systemd-networkd.service
  chroot systemctl enable systemd-resolved.service
  chroot ln -sf /run/systemd/resolve/stub-resolv.conf /etc/resolv.conf 
  chroot systemctl enable systemd-timesyncd.service
}



function wheelgrpcfg()
{
  lognl "Configure wheelgroup"
  # Ensure the wheel group exists and add user to it."
  chroot groupadd wheel
  chroot usermod -aG wheel polar
}

function sudocfg()
{
  lognl "==> Configure sudo ..."
  chroot echo "%sudo ALL=(ALL) ALL" > /etc/sudoers.d/10-sudo
  chroot groupadd sudo && log "==> Add sudo group" || error "==> Failed to add sudo group!"
  chroot usermod -aG sudo $USER && log "==> Add sudo for $USER" || error "==> Failed to add sudo to $USER!"
}

# TODO: 


function rootpwcfg()
{
  chroot usermod --password $ROOTPW root && log "==> Set root pw to ${ROOTPW}!" || error "==> Failed to set root pw!"
  echo -e "${ROOTPW}\n${ROOTPW}\n" | chroot ${ROOTFS} passwd root && log "==> Set root pw to ${ROOTPW}!" || error "==> Failed to set root pw!"
}



# Install Yay
function install_git_repo()
{
  local PATH=tmp/build
  mkdir -p "$ROOTFS/$PATH" && "$ROOTFS/$PATH" 
  git clone https://aur.archlinux.org/yay.git "$ROOTFS/$PATH"
  # chroot install.sh
}  


#================ TUI CONFIG ===================#
# Autostart does not work:
# https://serverfault.com/questions/1030047/how-do-i-disable-automatic-login-in-a-debian-live-standard-image/1030050#1030050
# https://unix.stackexchange.com/questions/669327/gettytty1-serivce-service-is-permanently-restarting-debian-11-live-iso

function copytui()
{
  log "copy $WORK/tui to ${MNT}/opt"
  cp -rv ${WORK}/tui  /opt
  $CHROOT chown root  /opt/tui/*
  $CHROOT chmod +x    /opt/tui/*

  cp -rv --parents ${WORK}/config/etc/systemd/system/getty\@tty1.service.d/autologin.conf \
                    ${MNT}/config/etc/systemd/system/getty\@tty1.service.d/autologin.conf       
}

function automount()
{
# automount 
cat <<EOF > ${ROOTFS}/etc/fstab
UUID=${UUID_ROOTFS}  /          ext4  errors=remount-ro  0  1
UUID=${UUID_DATAFS}  /data      vfat  uid=${IMAGE_USER},gid=${IMAGE_USER}  0  2
EOF
}

function tuiautostart()
{
log "create tui autostart on getty"
# file: /etc/systemd/system/getty\@tty1.service.d/override.conf
cat <<EOF > ${MNT}/etc/systemd/system/getty\@tty1.service.d/autologin.conf
[Service]
ExecStart=
ExecStart=-/usr/sbin/agetty --autologin root --login-program /root/tui/menu.sh --mode service --noissue --noclear %I $TERM
EOF

log "tui getty autostart done!" && log ""
}




# ===========================
# MAIN FUNCTIONS
# ===========================
_buildbasesys()
{
  about
  lognl "Starting build $(date +"%D %T")"
  sleep 2

  ### prepare ###
  unmounting
  partioning
  mounting

  ### base system ###
  basesystem

  ### config 1 ###
  fstabgen
  localecfg
  hostcfg

  ### bootloader ###
  bootloader

  ### config 2 ###
}

_configure()
{
  ### fresh mount ###
  unmounting
  mounting


  localecfg
  hostcfg

  $CHROOT locale-gen de_DE.UTF-8

  networkcfg
  networkenable

  rootpwcfg
  wheelgrpcfg

  #sudocfg #TODO: dont works
  copytui
  #automount
  #tuiautostart
}

fullbuild()
{
  _buildbasesys
  _configure
}

basebuild()
{
  _buildbasesys
}

updatecfg()
{
  _configure
}



# ============================================= #
#  CLI CALL FUNCTIONS
# ============================================= #
function fullbuild()
{ 
  [ -z ${TARGET} ] && log "You must specify a target!" && exit 1
  _buildbasesys



}




function update_tui()
{ 
  [ -z ${TARGET} ] && log "You must specify a target!" && exit 1
  unmounting && mounting ${TARGET}2 && \
  cp -rv tui ${ROOTFS}/root/tui && log "TUI is up to date!" || err "Failed to update TUI!"
}

function update_config()
{ 
  [ -z ${TARGET} ] && log "You must specify a target!" && exit 1
  unmounting && mounting ${TARGET}2 && \
  updatecfg && log "Config is up to date!" || err "Failed to update config!"
}

function enter_chroot()
{ 
  [ -z ${TARGET} ] && log "You must specify a target!" && usage && exit 1
  unmounting && mounting && chroot $ROOTFS
}





# ============================================= #
#  MAIN CLI
# ============================================= #

if [ ! -z $TARGET ]; then 

  if [ $UNMOUNT == "YES" ]; then
    unmountall
  fi

  if [ $FULLWIPE == "YES" ]; then
    fullwipe
  fi

  if [ $FULLBUILD == "YES" ]; then
    fullbuild
  fi

  if [ $BASEBUILD == "YES" ]; then
    basebuild
  fi

  if [ $UPDATE_TUI == "YES" ]; then
    update_tui
  fi

  if [ $UPDATE_CONFIG == "YES" ]; then
     update_config 
  fi

  if [ $ENTER_CHROOT == "YES" ]; then
      enter_chroot
  fi

  log "=================================="
  log "SUCCESS!"

else
  log "You must specify a argument with target!"
fi